[package]
name = "badlib"
version = "0.1.0"
edition = "2021"

[lints.rust]
missing_docs = "deny"

[lints.clippy]
cast_possible_truncation = "deny"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


